language: java

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libarchive-dev libjudy-dev pkg-config build-essential

before_script:
  - cd ..
  - git clone https://github.com/traildb/traildb
  - cd traildb

script:
  - ./autogen.sh
  - ./configure
  - make
  - make install
