jobs:
  include:
    # Run tests on linux
    - stage: test
      language: java
      cache:
        directories:
        - $HOME/.m2
      os:
      - linux
      sudo: required
      before_install:
      - ./install.sh
      install: true
      script:
      - mvn clean install
    # Run tests on mac and deploy binaries if deployment is enabled.
    - stage: test
      language: java
      os: osx
      osx_image: xcode8.1
      cache:
        directories:
        - $HOME/.m2
      sudo: required
      before_install:
      - ./install.sh
      install: true
      script:
      - mvn clena install
      deploy:
        provider: script
        skip_cleanup: true
        script: ./upload_mac.sh;
        on:
          branch: master
          tags: true
    # Deploy jar with both mac and linux binaries.
    - stage: deploy
      language: java
      cache:
        directories:
        - $HOME/.m2
      os:
      - linux
      sudo: required
      before_install:
      - ./install.sh
      install: true
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script: ./deploy.sh
        on:
          branch: master
          tags: true
