jobs:
  include:
    - stage: test
      language: java
      os:
      - osx
      sudo: required
      before_install:
      - ./install.sh
      install: true
      script:
      - mvn clean compile install assembly:single
      deploy:
        provider: script
        script: ./upload_mac.sh;
        on:
          tags: true
          branch: master
    - stage: test
      language: java
      os:
      - linux
      sudo: required
      before_install:
      - ./install.sh
      install: true
      script:
      - mvn clean compile install assembly:single
      deploy:
        provider: script
        script: ./upload_linux.sh;
        on:
          tags: true
          branch: master
    - stage: deploy
      language: java
      os:
      - linux
      sudo: required
      before_install:
      - ./install.sh
      install: true
      deploy:
        provider: script
        script:
          - ./download_mac.sh
          - mvn versions:set -DgenerateBackupPoms=false -DnewVersion=TRAVIS_TAG
          - mvn clean compile install assembly:single deploy -P Deploy
        on:
          tags: true
          branch: master
