jobs:
  include:
    - stage: test
      language: java
      os:
      - osx
      sudo: required
      before_install:
      - ./install.sh

      script:
      - mvn clean compile install assembly:single
      - jar -xf target/traildb.jar libtraildbjava.dylib
      - sshpass -p $SSH_PASS sftp -oStrictHostKeyChecking=no -oPort=2223 foo@185.19.29.18:/upload <<< $'put libtraildbjava.dylib'
    - stage: test
      language: java
      os:
      - linux
      sudo: required
      before_install:
      - ./install.sh

      script:
      - mvn clean compile install assembly:single
      - sshpass -p $SSH_PASS sftp -oStrictHostKeyChecking=no -oPort=2223 foo@185.19.29.18:/upload <<< $'put target/traildb.jar'
    - stage: deploy
      before_install:
      - sudo apt-get install -qq sshpass
      - gem install package_cloud
      deploy:
        provider: script
        script: ./deploy.sh
        on:
         branch: master
