jobs:
  include:
    - stage: test
      language: java
      os:
      - osx
      sudo: required
      before_install:
      - ./install.sh
      install: true
      script:
      - mvn clean compile install assembly:single
      - if [ "$TRAVIS_BRANCH" = "master" ]; then ./upload_mac.sh; fi
    - stage: test
      language: java
      os:
      - linux
      sudo: required
      before_install:
      - ./install.sh
      install: true
      script:
      - mvn clean compile install assembly:single
      - if [ "$TRAVIS_BRANCH" = "master" ]; then ./upload_linux.sh; fi
    - stage: deploy
      sudo: required
      install: true
      script:
      - if [ "$TRAVIS_BRANCH" = "master" ]; then ./deploy.sh; fi
