# Comes with traildb-java installed

FROM aholyoke/traildb-java

USER circleci:circleci

COPY . /home/circleci/traildb-java

RUN cd /home/circleci/ && sudo chown circleci:circleci -R traildb-java && cd traildb-java && mvn install -P Linux
