/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_sqooba_traildbj_TrailDBj */

#ifndef _Included_io_sqooba_traildbj_TrailDBj
#define _Included_io_sqooba_traildbj_TrailDBj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_sqooba_traildbj_TrailDBj
 * Method:    tdbConsInit
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_sqooba_traildbj_TrailDBj_tdbConsInit
  (JNIEnv *, jobject);

/*
 * Class:     io_sqooba_traildbj_TrailDBj
 * Method:    tdbConsOpen
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;[Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_io_sqooba_traildbj_TrailDBj_tdbConsOpen
  (JNIEnv *, jobject, jobject, jstring, jobjectArray, jlong);

/*
 * Class:     io_sqooba_traildbj_TrailDBj
 * Method:    tdbConsClose
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_sqooba_traildbj_TrailDBj_tdbConsClose
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_sqooba_traildbj_TrailDBj
 * Method:    tdbConsAdd
 * Signature: (Ljava/nio/ByteBuffer;[BJ[Ljava/lang/String;[J)I
 */
JNIEXPORT jint JNICALL Java_io_sqooba_traildbj_TrailDBj_tdbConsAdd
  (JNIEnv *, jobject, jobject, jbyteArray, jlong, jobjectArray, jlongArray);

/*
 * Class:     io_sqooba_traildbj_TrailDBj
 * Method:    tdbConsAppend
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_sqooba_traildbj_TrailDBj_tdbConsAppend
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     io_sqooba_traildbj_TrailDBj
 * Method:    tdbConsFinalize
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_sqooba_traildbj_TrailDBj_tdbConsFinalize
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
